/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hangman;
import java.util.HashSet;

/**
 *
 * @author Shane
 */
public class Sodoku extends javax.swing.JFrame {

    /**
     * Creates new form Sodoku
     */
    public Sodoku() {
        initComponents();
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        square6_2 = new javax.swing.JTextField();
        square0_7 = new javax.swing.JTextField();
        square3_8 = new javax.swing.JTextField();
        square0_2 = new javax.swing.JTextField();
        square5_8 = new javax.swing.JTextField();
        square3_4 = new javax.swing.JTextField();
        square0_4 = new javax.swing.JTextField();
        square0_6 = new javax.swing.JTextField();
        square0_5 = new javax.swing.JTextField();
        square0_1 = new javax.swing.JTextField();
        square8_2 = new javax.swing.JTextField();
        square1_1 = new javax.swing.JTextField();
        square2_5 = new javax.swing.JTextField();
        square1_3 = new javax.swing.JTextField();
        square1_4 = new javax.swing.JTextField();
        square5_1 = new javax.swing.JTextField();
        square1_5 = new javax.swing.JTextField();
        square1_7 = new javax.swing.JTextField();
        square1_0 = new javax.swing.JTextField();
        square3_7 = new javax.swing.JTextField();
        square1_2 = new javax.swing.JTextField();
        square2_2 = new javax.swing.JTextField();
        square2_3 = new javax.swing.JTextField();
        square2_4 = new javax.swing.JTextField();
        square1_6 = new javax.swing.JTextField();
        square2_6 = new javax.swing.JTextField();
        square1_8 = new javax.swing.JTextField();
        square6_1 = new javax.swing.JTextField();
        square2_0 = new javax.swing.JTextField();
        square3_1 = new javax.swing.JTextField();
        square5_0 = new javax.swing.JTextField();
        square6_0 = new javax.swing.JTextField();
        square7_2 = new javax.swing.JTextField();
        square3_5 = new javax.swing.JTextField();
        square3_0 = new javax.swing.JTextField();
        square4_8 = new javax.swing.JTextField();
        square8_3 = new javax.swing.JTextField();
        square3_3 = new javax.swing.JTextField();
        square0_8 = new javax.swing.JTextField();
        square5_2 = new javax.swing.JTextField();
        square2_8 = new javax.swing.JTextField();
        square4_0 = new javax.swing.JTextField();
        square4_1 = new javax.swing.JTextField();
        square4_2 = new javax.swing.JTextField();
        square3_6 = new javax.swing.JTextField();
        square5_5 = new javax.swing.JTextField();
        square4_5 = new javax.swing.JTextField();
        square4_6 = new javax.swing.JTextField();
        square5_7 = new javax.swing.JTextField();
        square0_3 = new javax.swing.JTextField();
        square0_0 = new javax.swing.JTextField();
        square4_3 = new javax.swing.JTextField();
        square4_4 = new javax.swing.JTextField();
        square6_8 = new javax.swing.JTextField();
        square2_1 = new javax.swing.JTextField();
        square8_0 = new javax.swing.JTextField();
        square4_7 = new javax.swing.JTextField();
        square8_8 = new javax.swing.JTextField();
        square8_5 = new javax.swing.JTextField();
        square5_3 = new javax.swing.JTextField();
        square7_3 = new javax.swing.JTextField();
        square8_4 = new javax.swing.JTextField();
        square7_5 = new javax.swing.JTextField();
        square3_2 = new javax.swing.JTextField();
        square7_8 = new javax.swing.JTextField();
        square7_0 = new javax.swing.JTextField();
        square5_6 = new javax.swing.JTextField();
        square6_3 = new javax.swing.JTextField();
        square6_4 = new javax.swing.JTextField();
        square6_5 = new javax.swing.JTextField();
        square6_6 = new javax.swing.JTextField();
        square8_6 = new javax.swing.JTextField();
        square8_7 = new javax.swing.JTextField();
        square7_1 = new javax.swing.JTextField();
        square8_1 = new javax.swing.JTextField();
        square6_7 = new javax.swing.JTextField();
        square7_4 = new javax.swing.JTextField();
        square5_4 = new javax.swing.JTextField();
        square7_6 = new javax.swing.JTextField();
        square7_7 = new javax.swing.JTextField();
        square2_7 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 440));
        setSize(new java.awt.Dimension(600, 400));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        square6_2.setEditable(false);
        square6_2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square6_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square6_2.setText("2");
        square6_2.setBorder(null);
        square6_2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square6_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square6_2ActionPerformed(evt);
            }
        });
        jPanel1.add(square6_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 40, 40));

        square0_7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square0_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square0_7.setBorder(null);
        square0_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square0_7ActionPerformed(evt);
            }
        });
        jPanel1.add(square0_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 40, 40));

        square3_8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square3_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square3_8.setBorder(null);
        square3_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square3_8ActionPerformed(evt);
            }
        });
        jPanel1.add(square3_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 40, 40));

        square0_2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square0_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square0_2.setBorder(null);
        square0_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square0_2ActionPerformed(evt);
            }
        });
        jPanel1.add(square0_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 40, 40));

        square5_8.setEditable(false);
        square5_8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square5_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square5_8.setText("3");
        square5_8.setBorder(null);
        square5_8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square5_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square5_8ActionPerformed(evt);
            }
        });
        jPanel1.add(square5_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 40, 40));

        square3_4.setEditable(false);
        square3_4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square3_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square3_4.setText("3");
        square3_4.setBorder(null);
        square3_4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square3_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square3_4ActionPerformed(evt);
            }
        });
        jPanel1.add(square3_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 40, 40));

        square0_4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square0_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square0_4.setBorder(null);
        square0_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square0_4ActionPerformed(evt);
            }
        });
        jPanel1.add(square0_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 40, 40));

        square0_6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square0_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square0_6.setBorder(null);
        square0_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square0_6ActionPerformed(evt);
            }
        });
        jPanel1.add(square0_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 40, 40));

        square0_5.setEditable(false);
        square0_5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square0_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square0_5.setText("6");
        square0_5.setBorder(null);
        square0_5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square0_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square0_5ActionPerformed(evt);
            }
        });
        jPanel1.add(square0_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 40, 40));

        square0_1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square0_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square0_1.setBorder(null);
        square0_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square0_1ActionPerformed(evt);
            }
        });
        jPanel1.add(square0_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 40));

        square8_2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square8_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square8_2.setBorder(null);
        square8_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square8_2ActionPerformed(evt);
            }
        });
        jPanel1.add(square8_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 40, 40));

        square1_1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square1_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square1_1.setBorder(null);
        square1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square1_1ActionPerformed(evt);
            }
        });
        jPanel1.add(square1_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 40, 40));

        square2_5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square2_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square2_5.setBorder(null);
        square2_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square2_5ActionPerformed(evt);
            }
        });
        jPanel1.add(square2_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 40, 40));

        square1_3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square1_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square1_3.setBorder(null);
        square1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square1_3ActionPerformed(evt);
            }
        });
        jPanel1.add(square1_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 40, 40));

        square1_4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square1_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square1_4.setBorder(null);
        square1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square1_4ActionPerformed(evt);
            }
        });
        jPanel1.add(square1_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 40, 40));

        square5_1.setEditable(false);
        square5_1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square5_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square5_1.setText("4");
        square5_1.setBorder(null);
        square5_1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square5_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square5_1ActionPerformed(evt);
            }
        });
        jPanel1.add(square5_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 40, 40));

        square1_5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square1_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square1_5.setBorder(null);
        square1_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square1_5ActionPerformed(evt);
            }
        });
        jPanel1.add(square1_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 40, 40));

        square1_7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square1_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square1_7.setBorder(null);
        square1_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square1_7ActionPerformed(evt);
            }
        });
        jPanel1.add(square1_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 40, 40));

        square1_0.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square1_0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square1_0.setBorder(null);
        square1_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square1_0ActionPerformed(evt);
            }
        });
        jPanel1.add(square1_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 40, 40));

        square3_7.setEditable(false);
        square3_7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square3_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square3_7.setText("8");
        square3_7.setBorder(null);
        square3_7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square3_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square3_7ActionPerformed(evt);
            }
        });
        jPanel1.add(square3_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 40, 40));

        square1_2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square1_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square1_2.setBorder(null);
        square1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square1_2ActionPerformed(evt);
            }
        });
        jPanel1.add(square1_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 40, 40));

        square2_2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square2_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square2_2.setBorder(null);
        square2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square2_2ActionPerformed(evt);
            }
        });
        jPanel1.add(square2_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 40, 40));

        square2_3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square2_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square2_3.setBorder(null);
        square2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square2_3ActionPerformed(evt);
            }
        });
        jPanel1.add(square2_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 40, 40));

        square2_4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square2_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square2_4.setBorder(null);
        square2_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square2_4ActionPerformed(evt);
            }
        });
        jPanel1.add(square2_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 40, 40));

        square1_6.setEditable(false);
        square1_6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square1_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square1_6.setText("4");
        square1_6.setBorder(null);
        square1_6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square1_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square1_6ActionPerformed(evt);
            }
        });
        jPanel1.add(square1_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 40, 40));

        square2_6.setEditable(false);
        square2_6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square2_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square2_6.setText("6");
        square2_6.setBorder(null);
        square2_6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square2_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square2_6ActionPerformed(evt);
            }
        });
        jPanel1.add(square2_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 40, 40));

        square1_8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square1_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square1_8.setBorder(null);
        square1_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square1_8ActionPerformed(evt);
            }
        });
        jPanel1.add(square1_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 40, 40));

        square6_1.setEditable(false);
        square6_1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square6_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square6_1.setText("5");
        square6_1.setBorder(null);
        square6_1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square6_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square6_1ActionPerformed(evt);
            }
        });
        jPanel1.add(square6_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 40, 40));

        square2_0.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square2_0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square2_0.setBorder(null);
        square2_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square2_0ActionPerformed(evt);
            }
        });
        jPanel1.add(square2_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 40, 40));

        square3_1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square3_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square3_1.setBorder(null);
        square3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square3_1ActionPerformed(evt);
            }
        });
        jPanel1.add(square3_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 40, 40));

        square5_0.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square5_0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square5_0.setBorder(null);
        square5_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square5_0ActionPerformed(evt);
            }
        });
        jPanel1.add(square5_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 40, 40));

        square6_0.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square6_0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square6_0.setBorder(null);
        square6_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square6_0ActionPerformed(evt);
            }
        });
        jPanel1.add(square6_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 40, 40));

        square7_2.setEditable(false);
        square7_2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square7_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square7_2.setText("1");
        square7_2.setBorder(null);
        square7_2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square7_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square7_2ActionPerformed(evt);
            }
        });
        jPanel1.add(square7_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 40, 40));

        square3_5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square3_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square3_5.setBorder(null);
        square3_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square3_5ActionPerformed(evt);
            }
        });
        jPanel1.add(square3_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 40, 40));

        square3_0.setEditable(false);
        square3_0.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square3_0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square3_0.setText("5");
        square3_0.setBorder(null);
        square3_0.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square3_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square3_0ActionPerformed(evt);
            }
        });
        jPanel1.add(square3_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 40, 40));

        square4_8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square4_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square4_8.setBorder(null);
        square4_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square4_8ActionPerformed(evt);
            }
        });
        jPanel1.add(square4_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 40, 40));

        square8_3.setEditable(false);
        square8_3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square8_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square8_3.setText("9");
        square8_3.setBorder(null);
        square8_3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square8_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square8_3ActionPerformed(evt);
            }
        });
        jPanel1.add(square8_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 40, 40));

        square3_3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square3_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square3_3.setBorder(null);
        square3_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square3_3ActionPerformed(evt);
            }
        });
        jPanel1.add(square3_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 40, 40));

        square0_8.setEditable(false);
        square0_8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square0_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square0_8.setText("7");
        square0_8.setBorder(null);
        square0_8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square0_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square0_8ActionPerformed(evt);
            }
        });
        jPanel1.add(square0_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 40, 40));

        square5_2.setEditable(false);
        square5_2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square5_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square5_2.setText("8");
        square5_2.setBorder(null);
        square5_2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square5_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square5_2ActionPerformed(evt);
            }
        });
        jPanel1.add(square5_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 40, 40));

        square2_8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square2_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square2_8.setBorder(null);
        square2_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square2_8ActionPerformed(evt);
            }
        });
        jPanel1.add(square2_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 40, 40));

        square4_0.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square4_0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square4_0.setBorder(null);
        square4_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square4_0ActionPerformed(evt);
            }
        });
        jPanel1.add(square4_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 40, 40));

        square4_1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square4_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square4_1.setBorder(null);
        square4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square4_1ActionPerformed(evt);
            }
        });
        jPanel1.add(square4_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 40, 40));

        square4_2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square4_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square4_2.setBorder(null);
        square4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square4_2ActionPerformed(evt);
            }
        });
        jPanel1.add(square4_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 40, 40));

        square3_6.setEditable(false);
        square3_6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square3_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square3_6.setText("7");
        square3_6.setBorder(null);
        square3_6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square3_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square3_6ActionPerformed(evt);
            }
        });
        jPanel1.add(square3_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 40, 40));

        square5_5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square5_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square5_5.setBorder(null);
        square5_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square5_5ActionPerformed(evt);
            }
        });
        jPanel1.add(square5_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 40, 40));

        square4_5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square4_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square4_5.setBorder(null);
        square4_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square4_5ActionPerformed(evt);
            }
        });
        jPanel1.add(square4_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 40, 40));

        square4_6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square4_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square4_6.setBorder(null);
        square4_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square4_6ActionPerformed(evt);
            }
        });
        jPanel1.add(square4_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 40, 40));

        square5_7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square5_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square5_7.setBorder(null);
        square5_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square5_7ActionPerformed(evt);
            }
        });
        jPanel1.add(square5_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 40, 40));

        square0_3.setEditable(false);
        square0_3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square0_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square0_3.setText("4");
        square0_3.setBorder(null);
        square0_3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square0_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square0_3ActionPerformed(evt);
            }
        });
        jPanel1.add(square0_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 40, 40));

        square0_0.setEditable(false);
        square0_0.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square0_0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square0_0.setText("8");
        square0_0.setBorder(null);
        square0_0.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square0_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square0_0ActionPerformed(evt);
            }
        });
        jPanel1.add(square0_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        square4_3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square4_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square4_3.setBorder(null);
        square4_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square4_3ActionPerformed(evt);
            }
        });
        jPanel1.add(square4_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 40, 40));

        square4_4.setEditable(false);
        square4_4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square4_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square4_4.setText("7");
        square4_4.setBorder(null);
        square4_4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square4_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square4_4ActionPerformed(evt);
            }
        });
        jPanel1.add(square4_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 40, 40));

        square6_8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square6_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square6_8.setBorder(null);
        square6_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square6_8ActionPerformed(evt);
            }
        });
        jPanel1.add(square6_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 40, 40));

        square2_1.setEditable(false);
        square2_1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square2_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square2_1.setText("1");
        square2_1.setBorder(null);
        square2_1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square2_1ActionPerformed(evt);
            }
        });
        jPanel1.add(square2_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 40, 40));

        square8_0.setEditable(false);
        square8_0.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square8_0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square8_0.setText("3");
        square8_0.setBorder(null);
        square8_0.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square8_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square8_0ActionPerformed(evt);
            }
        });
        jPanel1.add(square8_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 40, 40));

        square4_7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square4_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square4_7.setBorder(null);
        square4_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square4_7ActionPerformed(evt);
            }
        });
        jPanel1.add(square4_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 40, 40));

        square8_8.setEditable(false);
        square8_8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square8_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square8_8.setText("5");
        square8_8.setBorder(null);
        square8_8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square8_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square8_8ActionPerformed(evt);
            }
        });
        jPanel1.add(square8_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 40, 40));

        square8_5.setEditable(false);
        square8_5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square8_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square8_5.setText("2");
        square8_5.setBorder(null);
        square8_5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square8_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square8_5ActionPerformed(evt);
            }
        });
        jPanel1.add(square8_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 40, 40));

        square5_3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square5_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square5_3.setBorder(null);
        square5_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square5_3ActionPerformed(evt);
            }
        });
        jPanel1.add(square5_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 40, 40));

        square7_3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square7_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square7_3.setBorder(null);
        square7_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square7_3ActionPerformed(evt);
            }
        });
        jPanel1.add(square7_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 40, 40));

        square8_4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square8_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square8_4.setBorder(null);
        square8_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square8_4ActionPerformed(evt);
            }
        });
        jPanel1.add(square8_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 40, 40));

        square7_5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square7_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square7_5.setBorder(null);
        square7_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square7_5ActionPerformed(evt);
            }
        });
        jPanel1.add(square7_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 40, 40));

        square3_2.setEditable(false);
        square3_2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square3_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square3_2.setText("9");
        square3_2.setBorder(null);
        square3_2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square3_2ActionPerformed(evt);
            }
        });
        jPanel1.add(square3_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 40, 40));

        square7_8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square7_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square7_8.setBorder(null);
        square7_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square7_8ActionPerformed(evt);
            }
        });
        jPanel1.add(square7_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 40, 40));

        square7_0.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square7_0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square7_0.setBorder(null);
        square7_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square7_0ActionPerformed(evt);
            }
        });
        jPanel1.add(square7_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 40, 40));

        square5_6.setEditable(false);
        square5_6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square5_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square5_6.setText("1");
        square5_6.setBorder(null);
        square5_6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square5_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square5_6ActionPerformed(evt);
            }
        });
        jPanel1.add(square5_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 40, 40));

        square6_3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square6_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square6_3.setBorder(null);
        square6_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square6_3ActionPerformed(evt);
            }
        });
        jPanel1.add(square6_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 40, 40));

        square6_4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square6_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square6_4.setBorder(null);
        square6_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square6_4ActionPerformed(evt);
            }
        });
        jPanel1.add(square6_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 40, 40));

        square6_5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square6_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square6_5.setBorder(null);
        square6_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square6_5ActionPerformed(evt);
            }
        });
        jPanel1.add(square6_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 40, 40));

        square6_6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square6_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square6_6.setBorder(null);
        square6_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square6_6ActionPerformed(evt);
            }
        });
        jPanel1.add(square6_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 40, 40));

        square8_6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square8_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square8_6.setBorder(null);
        square8_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square8_6ActionPerformed(evt);
            }
        });
        jPanel1.add(square8_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 40, 40));

        square8_7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square8_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square8_7.setBorder(null);
        square8_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square8_7ActionPerformed(evt);
            }
        });
        jPanel1.add(square8_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 40, 40));

        square7_1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square7_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square7_1.setBorder(null);
        square7_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square7_1ActionPerformed(evt);
            }
        });
        jPanel1.add(square7_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 40, 40));

        square8_1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square8_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square8_1.setBorder(null);
        square8_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square8_1ActionPerformed(evt);
            }
        });
        jPanel1.add(square8_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 40, 40));

        square6_7.setEditable(false);
        square6_7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square6_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square6_7.setText("9");
        square6_7.setBorder(null);
        square6_7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square6_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square6_7ActionPerformed(evt);
            }
        });
        jPanel1.add(square6_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 40, 40));

        square7_4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square7_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square7_4.setBorder(null);
        square7_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square7_4ActionPerformed(evt);
            }
        });
        jPanel1.add(square7_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 40, 40));

        square5_4.setEditable(false);
        square5_4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square5_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square5_4.setText("2");
        square5_4.setBorder(null);
        square5_4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square5_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square5_4ActionPerformed(evt);
            }
        });
        jPanel1.add(square5_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 40, 40));

        square7_6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square7_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square7_6.setBorder(null);
        square7_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square7_6ActionPerformed(evt);
            }
        });
        jPanel1.add(square7_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 40, 40));

        square7_7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square7_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square7_7.setBorder(null);
        square7_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square7_7ActionPerformed(evt);
            }
        });
        jPanel1.add(square7_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 40, 40));

        square2_7.setEditable(false);
        square2_7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        square2_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        square2_7.setText("5");
        square2_7.setBorder(null);
        square2_7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        square2_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                square2_7ActionPerformed(evt);
            }
        });
        jPanel1.add(square2_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void square6_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square6_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square6_2ActionPerformed

    private void square0_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square0_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square0_7ActionPerformed

    private void square3_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square3_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square3_8ActionPerformed

    private void square0_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square0_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square0_2ActionPerformed

    private void square5_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square5_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square5_8ActionPerformed

    private void square3_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square3_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square3_4ActionPerformed

    private void square0_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square0_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square0_4ActionPerformed

    private void square0_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square0_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square0_6ActionPerformed

    private void square0_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square0_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square0_5ActionPerformed

    private void square0_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square0_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square0_1ActionPerformed

    private void square8_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square8_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square8_2ActionPerformed

    private void square1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square1_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square1_1ActionPerformed

    private void square2_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square2_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square2_5ActionPerformed

    private void square1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square1_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square1_3ActionPerformed

    private void square1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square1_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square1_4ActionPerformed

    private void square5_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square5_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square5_1ActionPerformed

    private void square1_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square1_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square1_5ActionPerformed

    private void square1_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square1_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square1_7ActionPerformed

    private void square1_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square1_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square1_0ActionPerformed

    private void square3_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square3_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square3_7ActionPerformed

    private void square1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square1_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square1_2ActionPerformed

    private void square2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square2_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square2_2ActionPerformed

    private void square2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square2_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square2_3ActionPerformed

    private void square2_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square2_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square2_4ActionPerformed

    private void square1_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square1_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square1_6ActionPerformed

    private void square2_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square2_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square2_6ActionPerformed

    private void square1_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square1_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square1_8ActionPerformed

    private void square6_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square6_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square6_1ActionPerformed

    private void square2_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square2_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square2_0ActionPerformed

    private void square3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square3_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square3_1ActionPerformed

    private void square5_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square5_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square5_0ActionPerformed

    private void square6_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square6_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square6_0ActionPerformed

    private void square7_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square7_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square7_2ActionPerformed

    private void square3_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square3_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square3_5ActionPerformed

    private void square3_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square3_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square3_0ActionPerformed

    private void square4_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square4_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square4_8ActionPerformed

    private void square8_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square8_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square8_3ActionPerformed

    private void square3_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square3_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square3_3ActionPerformed

    private void square0_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square0_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square0_8ActionPerformed

    private void square5_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square5_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square5_2ActionPerformed

    private void square2_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square2_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square2_8ActionPerformed

    private void square4_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square4_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square4_0ActionPerformed

    private void square4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square4_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square4_1ActionPerformed

    private void square4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square4_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square4_2ActionPerformed

    private void square3_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square3_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square3_6ActionPerformed

    private void square5_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square5_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square5_5ActionPerformed

    private void square4_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square4_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square4_5ActionPerformed

    private void square4_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square4_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square4_6ActionPerformed

    private void square5_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square5_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square5_7ActionPerformed

    private void square0_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square0_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square0_3ActionPerformed

    private void square0_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square0_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square0_0ActionPerformed

    private void square4_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square4_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square4_3ActionPerformed

    private void square4_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square4_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square4_4ActionPerformed

    private void square6_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square6_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square6_8ActionPerformed

    private void square2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square2_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square2_1ActionPerformed

    private void square8_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square8_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square8_0ActionPerformed

    private void square4_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square4_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square4_7ActionPerformed

    private void square8_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square8_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square8_8ActionPerformed

    private void square8_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square8_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square8_5ActionPerformed

    private void square5_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square5_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square5_3ActionPerformed

    private void square7_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square7_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square7_3ActionPerformed

    private void square8_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square8_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square8_4ActionPerformed

    private void square7_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square7_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square7_5ActionPerformed

    private void square3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square3_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square3_2ActionPerformed

    private void square7_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square7_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square7_8ActionPerformed

    private void square7_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square7_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square7_0ActionPerformed

    private void square5_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square5_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square5_6ActionPerformed

    private void square6_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square6_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square6_3ActionPerformed

    private void square6_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square6_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square6_4ActionPerformed

    private void square6_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square6_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square6_5ActionPerformed

    private void square6_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square6_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square6_6ActionPerformed

    private void square8_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square8_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square8_6ActionPerformed

    private void square8_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square8_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square8_7ActionPerformed

    private void square7_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square7_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square7_1ActionPerformed

    private void square8_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square8_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square8_1ActionPerformed

    private void square6_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square6_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square6_7ActionPerformed

    private void square7_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square7_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square7_4ActionPerformed

    private void square5_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square5_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square5_4ActionPerformed

    private void square7_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square7_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square7_6ActionPerformed

    private void square7_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square7_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square7_7ActionPerformed

    private void square2_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_square2_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_square2_7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sodoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sodoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sodoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sodoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sodoku().setVisible(true);
            }
        });
    }
    
    private boolean checkGuess(String guess, int yPos, int xPos){
        HashSet<String> acceptableInputs = new HashSet<String>(9);
        acceptableInputs.add("1");
        acceptableInputs.add("2");
        acceptableInputs.add("3");
        acceptableInputs.add("4");
        acceptableInputs.add("5");
        acceptableInputs.add("6");
        acceptableInputs.add("7");
        acceptableInputs.add("8");
        acceptableInputs.add("9");
        
        return false;
        
    }

    private int[][] sodokuKey = 
    {{8,3,5,4,1,6,9,2,7},
     {2,9,6,8,5,7,4,3,1},
     {4,1,7,2,9,3,6,5,8},
     {5,6,9,1,3,4,7,8,2},
     {1,2,3,6,7,8,5,4,9},
     {7,4,8,5,2,9,1,6,3},
     {6,5,2,7,8,1,3,9,4},
     {9,8,1,3,4,5,2,7,6},
     {3,7,4,9,6,2,8,1,5}
    };
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField square0_0;
    private javax.swing.JTextField square0_1;
    private javax.swing.JTextField square0_2;
    private javax.swing.JTextField square0_3;
    private javax.swing.JTextField square0_4;
    private javax.swing.JTextField square0_5;
    private javax.swing.JTextField square0_6;
    private javax.swing.JTextField square0_7;
    private javax.swing.JTextField square0_8;
    private javax.swing.JTextField square1_0;
    private javax.swing.JTextField square1_1;
    private javax.swing.JTextField square1_2;
    private javax.swing.JTextField square1_3;
    private javax.swing.JTextField square1_4;
    private javax.swing.JTextField square1_5;
    private javax.swing.JTextField square1_6;
    private javax.swing.JTextField square1_7;
    private javax.swing.JTextField square1_8;
    private javax.swing.JTextField square2_0;
    private javax.swing.JTextField square2_1;
    private javax.swing.JTextField square2_2;
    private javax.swing.JTextField square2_3;
    private javax.swing.JTextField square2_4;
    private javax.swing.JTextField square2_5;
    private javax.swing.JTextField square2_6;
    private javax.swing.JTextField square2_7;
    private javax.swing.JTextField square2_8;
    private javax.swing.JTextField square3_0;
    private javax.swing.JTextField square3_1;
    private javax.swing.JTextField square3_2;
    private javax.swing.JTextField square3_3;
    private javax.swing.JTextField square3_4;
    private javax.swing.JTextField square3_5;
    private javax.swing.JTextField square3_6;
    private javax.swing.JTextField square3_7;
    private javax.swing.JTextField square3_8;
    private javax.swing.JTextField square4_0;
    private javax.swing.JTextField square4_1;
    private javax.swing.JTextField square4_2;
    private javax.swing.JTextField square4_3;
    private javax.swing.JTextField square4_4;
    private javax.swing.JTextField square4_5;
    private javax.swing.JTextField square4_6;
    private javax.swing.JTextField square4_7;
    private javax.swing.JTextField square4_8;
    private javax.swing.JTextField square5_0;
    private javax.swing.JTextField square5_1;
    private javax.swing.JTextField square5_2;
    private javax.swing.JTextField square5_3;
    private javax.swing.JTextField square5_4;
    private javax.swing.JTextField square5_5;
    private javax.swing.JTextField square5_6;
    private javax.swing.JTextField square5_7;
    private javax.swing.JTextField square5_8;
    private javax.swing.JTextField square6_0;
    private javax.swing.JTextField square6_1;
    private javax.swing.JTextField square6_2;
    private javax.swing.JTextField square6_3;
    private javax.swing.JTextField square6_4;
    private javax.swing.JTextField square6_5;
    private javax.swing.JTextField square6_6;
    private javax.swing.JTextField square6_7;
    private javax.swing.JTextField square6_8;
    private javax.swing.JTextField square7_0;
    private javax.swing.JTextField square7_1;
    private javax.swing.JTextField square7_2;
    private javax.swing.JTextField square7_3;
    private javax.swing.JTextField square7_4;
    private javax.swing.JTextField square7_5;
    private javax.swing.JTextField square7_6;
    private javax.swing.JTextField square7_7;
    private javax.swing.JTextField square7_8;
    private javax.swing.JTextField square8_0;
    private javax.swing.JTextField square8_1;
    private javax.swing.JTextField square8_2;
    private javax.swing.JTextField square8_3;
    private javax.swing.JTextField square8_4;
    private javax.swing.JTextField square8_5;
    private javax.swing.JTextField square8_6;
    private javax.swing.JTextField square8_7;
    private javax.swing.JTextField square8_8;
    // End of variables declaration//GEN-END:variables
}
